.PHONY: clean All

All:
	@echo "----------Building project:[ StartingSequenceMakerTest - Debug ]----------"
	@cd "StartingSequenceMakerTest" && "$(MAKE)" -f  "StartingSequenceMakerTest.mk"
clean:
	@echo "----------Cleaning project:[ StartingSequenceMakerTest - Debug ]----------"
	@cd "StartingSequenceMakerTest" && "$(MAKE)" -f  "StartingSequenceMakerTest.mk" clean
